// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiV-cG4Ir3kL9_Wd7KZQUuH9-TJ40dosY',
    appId: '1:181239189384:web:ab97e84612a1d5067a343d',
    messagingSenderId: '181239189384',
    projectId: 'fooddeliveryapp-785a0',
    authDomain: 'fooddeliveryapp-785a0.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-785a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWVEJunIScMMTO_jvU8vA1MB5z5fYeqOw',
    appId: '1:181239189384:android:7e4f50e390e50ddd7a343d',
    messagingSenderId: '181239189384',
    projectId: 'fooddeliveryapp-785a0',
    storageBucket: 'fooddeliveryapp-785a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4u50e5SRWC5n4nZGad2hTtLvHWfoTKgI',
    appId: '1:181239189384:ios:dfadb641d045c3697a343d',
    messagingSenderId: '181239189384',
    projectId: 'fooddeliveryapp-785a0',
    storageBucket: 'fooddeliveryapp-785a0.appspot.com',
    iosClientId: '181239189384-66500bhv19bfl308qvuc8tnof39u7et5.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminWebPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4u50e5SRWC5n4nZGad2hTtLvHWfoTKgI',
    appId: '1:181239189384:ios:dfadb641d045c3697a343d',
    messagingSenderId: '181239189384',
    projectId: 'fooddeliveryapp-785a0',
    storageBucket: 'fooddeliveryapp-785a0.appspot.com',
    iosClientId: '181239189384-66500bhv19bfl308qvuc8tnof39u7et5.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminWebPortal',
  );
}
