name: seller_app
description: Dierb merchant app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dierb_core:
    path: ../packages/dierb_core
  cupertino_icons: ^1.0.2
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.0
  cloud_firestore: ^6.9.0
  firebase_storage: ^13.5.0
  firebase_messaging: ^16.1.1
  image_picker: ^0.8.9
  http: ^1.2.2
  geolocator: ^9.0.2
  geocoding: ^4.0.0
  shared_preferences: ^2.1.0
  flutter_staggered_grid_view: ^0.4.1
  fluttertoast: ^10.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
