name: rider_app
description: Dierb rider app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dierb_core:
    path: ../packages/dierb_core
  cupertino_icons: ^1.0.2
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.0
  cloud_firestore: ^6.9.0
  firebase_storage: ^13.5.0
  firebase_messaging: ^16.1.1
  fluttertoast: ^10.0.0
  image_picker: ^0.8.9
  geolocator: ^9.0.2
  geocoding: ^4.0.0
  shared_preferences: ^2.1.0
  url_launcher: ^6.3.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
